language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
    - os: osx # OSX 10.11
      osx_image: xcode8
      dotnet: 1.0.0-preview2-003131
      mono: none
install:
    - dotnet restore
script:
    - dotnet test
